apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: dev04
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
